export const fakeUsers = [
	['goku798', '#c365b0'],
	['dazzle_razzle', '#9ffbe2'],
	['reallysubverted', '#ff4a5f'],
	['dalybeet21', '#359bff'],
	['JanyceMaria', '#5f9ea0'],
	['jeesejeep', '#ff69b4'],
	['UnusedSteer', '#e1762a'],
	['kitsu_', '#359dd8'],
	['suzki31', '#ff7f50'],
	['trianglevigor', '#ff69b4'],
	['pglad', '#00e700'],
	['thesleepypiranha', '#aa64ea'],
	['LookItsArcher', '#ff69b4'],
	['pizzapoggers', '#e1762a'],
	['hottopicgraduate', '#00ff7f'],
	['ftarbl', '#00ff7f'],
	['AlwaysBeClimbing', '#359bff'],
	['General_Jackal', '#ff5858'],
	['WackyBelly', '#aa64ea'],
	['Prof_FickleKits', '#3db974'],
	['OzzieInShoes', '#7878ff'],
	['Somebody1', null],
	['Somebody2', null],
	['Somebody3', null],
	['Somebody4', null],
	['Somebody5', null],
]

export const graceMessages = [
	'grace',
	'GRACE',
	'G R A C E',
	'grace!!!',
	'GRACE!',
	'GRACE TRAIN!',
	'GrAcE',
	'🙏',
]
export const trainBreakingMessages = [
	'c-c-c-combo breaker!',
	'hello everyone!',
	'lol',
	'wow',
	'woah',
	"what's happening?",
	"what's going on?",
]
export const regretMessages = [
	'LOL SORRY',
	'oh oops',
	'OH GOD',
	'OH NO I BROKE IT',
	'oops sorry',
]
export const afterTrainMessages = [
	'that was great',
	'good grace train',
	'very good grace train',
	'very good',
	'good work everyone',
	'that was a long one',
	'you broke it',
	'lol',
	'haha',
	'nice',
	'wow',
	'wow what a train!',
	'good stuff',
]
